### ISSUE TITLE
GUI is providing default values not consistent with CLI

### ISSUE THREAD

**Issue by bkabrda** [devassistant/devassistant#149]
I have an argument like this:

```
  py3:
    flags:
    - --py3
    action: store_const
    const: 3
    default: ''
    help: 'Use Python 3 instead of Python 2.'
```

But when it's not specified, GUI makes it's default value "False", not empty string. Not sure if it's caused by core or GUI, though.
