### ISSUE TITLE
gh-fork should use value from .gitconfig if exists

### ISSUE THREAD

**Issue by xsuchy** [devassistant/devassistant#256]
assistants/prep/custom.yaml and maybe other contains:

```
  gh_fork:
    flags: [--gh-fork]
    help: Fork the repo, assuming it's on Github. Pass your GH username as argument if it's
          different from your system username.
    action: [default_iff_used, '']
    nargs: '?'
    gui_hints:
      default: $(whoami)
```

where $whoami is my local username (msuchy in my case). Where I have in ~/.gitconfig already:

```
[github "user"]
xsuchy = xsuchy
```

It would be nice if the default value can be this value (if present in .gitconfig). And only if not present then the default may be my local username.
Otherwise I have to specify it every time again and again and again.
