### ISSUE TITLE
Snippet invoking function from self fails if dependencies are specified

### ISSUE THREAD

**Issue by tradej** [devassistant/devassistant#263]
The following snippet (named `broken.py`, in my case) fails with `ERROR: No runner for command "rpm: ['kernel']".` if it's invoked from an assistant with `use: broken.run`

``` yaml
dependencies:
- rpm: ['kernel']

run:
- use: broken.section1

section1:
- log_i: Section1
```
