### ISSUE TITLE
"use" command runner should be able to "pass arguments"

### ISSUE THREAD

**Issue by bkabrda** [devassistant/devassistant#283]
It should be possible to "pass arguments" to called sections, something along the lines of:

```
- use:
    sect: run_something
    args:
      foo: $something
      bar: $something_else
```

Doing this will allow us to pass variables under different names (impossible now), pass literals to functions without having to assign them to variables first and generally have a better control of called section scope.

It seems that we can preserve current behaviour (for now), since we can safely distinguish these two ways by what is passed to `use` command runner (string for the present behaviour, dictionary for the proposed behaviour).
