### ISSUE TITLE
got TypeError traceback after using positional arguments

### ISSUE THREAD

**Issue by TomasTomecek** [devassistant/devassistant#320]
Am trying out da 0.10.0. Started with writing my own tweak assistant:

``` yaml
args:                                                                                                                                                                                         
  bin:                                                                                                                                                                                        
    flags:                                                                                                                                                                                    
      - -b                                                                                                                                                                                  
      - --bin                                                                                                                                                                               
    action: store_const                                                                                                                                                                       
    const: fedpkg                                                                                                                                                                             
    default: 'fedpkg'                                                                                                                                                                         
    help:                                                                                                                                                                                     
      'rpkg binary'                                                                                                                                                                           
  package:                                                                                                                                                                                    
    flags: [package]                                                                                                                                                                          
    action: store_const                                                                                                                                                                       
    help:                                                                                                                                                                                     
      'package to clone'                                                                                                                                                                      
  branch:                                                                                                                                                                                     
    flags: [branch]                                                                                                                                                                           
    action: store_const                                                                                                                                                                       
    help:                                                                                                                                                                                     
      'branch to checkout'                                                                                                                                                                    
run:                                                                                                                                                                                          
  - cl: $bin clone $package        
```

As you can see, I'm trying to use positional arguments. Unfortunately, after running `da twk` (I modified my da loader path) I get this traceback:

```
$ da twk
Traceback (most recent call last):
  File "/bin/da", line 9, in <module>
    load_entry_point('devassistant==0.10.0', 'console_scripts', 'da')()
  File "/usr/lib/python2.7/site-packages/devassistant/cli/cli_runner.py", line 56, in run
    generate_argument_parser(tree, actions=actions.actions)
  File "/usr/lib/python2.7/site-packages/devassistant/cli/argparse_generator.py", line 45, in generate_argument_parser
    cls.add_subassistants_to(subparsers, subas, level=1, alias=alias)
  File "/usr/lib/python2.7/site-packages/devassistant/cli/argparse_generator.py", line 85, in add_subassistants_to
    cls.add_subassistants_to(subparsers, subas_tuple, level + 1)
  File "/usr/lib/python2.7/site-packages/devassistant/cli/argparse_generator.py", line 85, in add_subassistants_to
    cls.add_subassistants_to(subparsers, subas_tuple, level + 1)
  File "/usr/lib/python2.7/site-packages/devassistant/cli/argparse_generator.py", line 77, in add_subassistants_to
    arg.add_argument_to(p)
  File "/usr/lib/python2.7/site-packages/devassistant/argument.py", line 49, in add_argument_to
    parser.add_argument(*self.flags, **self.kwargs)
  File "/usr/lib64/python2.7/argparse.py", line 1287, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() takes at least 4 arguments (6 given)
```

Are positional arguments supported?
